[package]
name = "wasmtime-runtime"
version = "0.9.0"
authors = ["The Wasmtime Project Developers"]
description = "Runtime library support for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition = "2018"

[dependencies]
wasmtime-environ = { path = "../environ", version = "0.9.0" }
region = "2.0.0"
lazy_static = "1.2.0"
libc = { version = "0.2.60", default-features = false }
memoffset = "0.5.3"
indexmap = "1.0.2"
thiserror = "1.0.4"
more-asserts = "0.2.1"
cfg-if = "0.1.9"
backtrace = "0.3.42"
#wasmeval = { path = "../../../wasmeval", optional = true }
wasmeval = { git = "https://github.com/yurydelendik/wasmeval", rev="a922ef4", optional = true }
target-lexicon = { version = "0.10.0", default-features = false }

cranelift-codegen = { version = "0.56", features = ["enable-serde"] }
cranelift-entity = { version = "0.56", features = ["enable-serde"] }
cranelift-wasm = { version = "0.56", features = ["enable-serde"] }
cranelift-native = "0.56"
cranelift-frontend = "0.56"


[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.7", features = ["winbase", "memoryapi"] }

[build-dependencies]
cc = "1.0"

[features]
interpreter = ["wasmeval", "wasmtime-environ/interpreter"]

[badges]
maintenance = { status = "actively-developed" }
